@startuml Analysis
!include <C4/C4_Component>

interface ICommandHandler {
   + handle(command)
}
interface IQueryHandler {
   + data handle(query)
}
class FoodCounter {
    + ICommandHandler
    + IQueryHandler
    + command(CreatePurchaiseRequest)
    + query(CollectFoodConsumptionData)
    + analyse()
}
class DataCollector { 
    + IQueryHandler
    + IDataMapper
    + query(CollectPurchaiseReceipts)
}
interface IDataMapper {
    + Map(purchaiseReceipts)
}
interface ISyncGate {
    + IDataMapper
    + send(mappedData) 
}

FoodCounter --> ICommandHandler : send command
FoodCounter --> IQueryHandler : send query

DataCollector --> IQueryHandler : send query
DataCollector --> IDataMapper :  map data to correct format 
DataCollector --> ISyncGate : send data to sync

@enduml