@startuml Архитектура_АвтоТехноСвиноКомплекс_v1_Альтернативное_Решение
!include <C4/C4_Context>


Person(duty_operator, "Дежурный оператор")
Person(operator, "Оператор")
Person(analytic, "Аналитик")
Person(vet, "Ветеринар")

System(atck_agent, "АвтоТехноСвиноКомплекс - Агент")
System(atck_server, "АвтоТехноСвиноКомплекс - Сервер")
BiRel(atck_agent, atck_server, "Синхронизирует данные")

Rel(atck_agent, duty_operator, "Получает уведомления")
Rel(atck_agent, operator, "Получает задачи на обслуживание")
Rel(atck_agent, vet, "Получает данные о животных")
Rel(analytic, atck_server, "Управляет метриками")

System_Ext(analytic_module, "Аналитический модуль")
System_Ext(erp, "ERP - система")

Rel(atck_server, analytic_module, "Передает данные метрик")
Rel(atck_server, erp, "Отправляет заявки на закупку кормов")
@enduml