@startuml Архитектура_АвтоТехноСвиноКомплекс_v1_Альтернативное_Решение
!include <C4/C4_Context>

Person(duty_operator, "Дежурный оператор")

System(atck, "АвтоТехноСвиноКомплекс")

Rel(atck, duty_operator, "Получает уведомления")

System_Ext(open_telemetry, "OpenTelemetry")
System_Ext(api, "API service")

Rel(atck, open_telemetry, "Отправляет метрики")
Rel(atck, api, "Предоставляет заявки на закупку кормов")
Rel(atck, api, "Предоставляет задачи на обслуживание")
Rel(atck, api, "Предоставляет данные о животных")
Rel(atck, api, "Получает данные о новых метриках")
@enduml