@startuml Архитектура_АвтоТехноСвиноКомплекс_v1_Альтернативное_Решение
!include <C4/C4_Container>


System_Boundary(atck_agent, "Agent"){
    ContainerQueue(broker, "Message broker")
    Boundary(b_video, "Video"){
        Container(video, "Video analysis")
        Container(notification, "Notifications")
        Rel(video, broker, "send events")
        Rel(video, notification, "send notification")
        Person(duty_operator, "Duty Operator")
        Rel(notification, duty_operator, "Recieves notification")
    }
    Lay_L(broker, b_video)
    Container(iot, "IOT data collecting")
    Rel(iot, broker, "sensors data")
    Rel(iot, broker, "RFID data")

    ContainerQueue(event_broker, "Event broker")
    
    Container(data, "Data Lake")
    Rel(broker, data, "raw data from Iot sensors")

    Container(iot_management, "Manage IoT devices")
    Rel(iot_management, data, "request data")
    Rel(iot_management, broker, "commands for IoT device")
    Rel(iot_management, event_broker, "tasks for people")  
    
    Container(prediction, "Prediction data service")
    Rel(prediction, data, "request data")
    Rel(prediction, event_broker, "commands for erp (buy food for pigs)")
            
    Container(pigs, "Pigs management")
    Rel(pigs, data, "request data")
    Rel(pigs, event_broker, "pigs data")
        
    Container(tasks, "Tasks management")
    Rel(event_broker, tasks, "get commands for people")
    Rel(event_broker, tasks, "get results of command executions")
    Rel(event_broker, tasks, "get people data (ERP)")
    Rel(tasks, event_broker, "send personificated commands")
    Boundary(b_ui, "UI"){
        Container(ui, "Offline Mobile or Web application")
        Boundary(users, "Users"){
            Person(operator, "Operator")
            Person(vet, "Vet")
        }
    }
    Rel(ui, operator, "Uses: tasks")
    Rel(ui, vet, "Uses: health data for pigs")
    BiRel(ui, event_broker, "send/receive commands")
    
    Boundary(b_erp, "Erp Sync"){
        System_Ext(erp, "ERP - system")
        Container(erp_sync, "ERP Sync gate")
        BiRel(erp_sync, event_broker, "send ERP-data")
        BiRel(erp, erp_sync, "Sync data")
    }
}

System_Boundary(atck_server, "Server"){
    Container(data_server, "Data Lake (on server)")
    BiRel(data, data_server, "sync data")

    System_Ext(analytic_module, "Analytic Module")
    
    Container(analytic_module_sync, "Analytic Sync gate")
    Rel(data_server, analytic_module_sync, "send metrics data")
    Rel(analytic_module_sync, analytic_module ,"send metrics data")
    
    Container(metrics, "Manage metrics")
    Rel(metrics, data_server, "create new metrics")
    Rel(data_server, metrics, "request metrics data")

    Container(ui_online, "Online Mobile or Web application")
    Person(analytic, "Analytic")
    Rel(analytic, ui_online, "Uses: metrics")
    BiRel(ui_online, metrics, "get metrics data and manage metrics")
    
}
Lay_D(event_broker, internal_services)
@enduml