@startuml Архитектура_АвтоТехноСвиноКомплекс_v1_Альтернативное_Решение
!include <C4/C4_Container>
!include <C4/C4_Container>

' === Участники ===
Person(duty_operator, "Дежурный оператор")
Person(technican, "Техник умных систем")
Person(cv_technican, "Техник видеонаблюдения")
Person(operator, "Оператор")
Person(vet, "Ветеринар")
Person(metric_admin, "Администратор метрик")

System(atck, "АвтоТехноСвиноКомплекс")
System_Ext(analytic, "Аналитический модуль")
System_Ext(erp, "ERP - система")

System_Boundary(atck, "АвтоТехноСвиноКомплекс"){
    Container(c_video, "Видеонаблюдение", "Анализ видео с камер наблюдения")
    Container(c_iot, "Умные устройства", "Управление и анализ данных с умных устройств")
    Container(c_registry, "Учет животных", "Учет состояния животных")
    Container(c_analytic, "Внутренняя аналитика", "Анализ текущих показателей фермы и прогнозирование")
}

Rel(c_video, c_registry, "Отправляет события о поведении животных")
Rel(c_video, c_analytic, "Отправляет события о поведении животных")
Rel(c_video, analytic, "Отправляет события о поведении животных")
Rel(cv_technican, c_video,"Вносит данные об установленных камерах")
Rel(c_video, cv_technican, "Получает задачи на обслуживание камер")
Rel(c_video, duty_operator, "Отсылает уведомление об опасном поведении животных")

Rel(c_iot, c_registry, "Отправляет события с датчиков умных устройств")
Rel(c_iot, c_analytic, "Отправляет события с датчиков умных устройств")
Rel(c_iot, analytic, "Отправляет события с датчиков умных устройств")
Rel(c_iot, operator, "Получает задачи на обслуживание умных устройств")

Rel(technican, c_iot,"Вносит данные о новых установленных умных устройствах")
Rel(c_iot, technican, "Получает задачи на обслуживание умных устройств")

Rel(operator, c_iot, "Вносит идентификационные данные о животных")

Rel(c_registry, vet, "Получает данные о здоровье животных")
Rel(c_registry, erp, "Отправляет данные о поголовье свиней")

Rel(c_analytic, erp, "Отправляет заявки на закупку кормов")
Rel(metric_admin, c_analytic,"Вносит данные о метриках")

Rel(c_analytic, analytic, "Отправляет данные метрик")

@enduml