@startuml Архитектура_АвтоТехноСвиноКомплекс_v1_Альтернативное_Решение
!include <C4/C4_Container>

System_Boundary(atck_agent, "Agent "){
    Person(duty_operator, "Duty Operator")
    ContainerQueue(data_hub, "Data Hub", "Store data, provide communication between containers")
    Container(video, "Video analysis", "Analyze data from cameras with AI")
    Rel(video, data_hub, "events")
    Rel(video, duty_operator, "notifications")
    
    Container(iot, "IoT sensors", "Sensors: temperature, volume, pressure, etc.")
    Container(iot, "IoT devices", "Can execute commands (open, close, on, off and so on)")
    Rel(iot, data_hub, "data")
    Container(iot_auto_management, "IOT auto-manage", "Analyze data from sensors and send commands to devices")
    Rel(iot_auto_management, data_hub, "commands")
    Rel(data_hub, iot_auto_management, "data")
    Container(iot_health_check, "IOT health check", "Check if Iot sensors or devices reuqire human help (clean, replace, repair and so on)")
    Rel(iot_health_check, data_hub, "tasks")
    Rel(data_hub, iot_health_check, "data")

    Boundary(internal_services, "Management services"){
        Container(supply, "Supply management", "Annalyses ammount fo food, and request to buy more")
        Container(pigs, "Pigs management", "Checks pigs status and health")
        Container(tasks, "Tasks management", "Manages tasks for operators")
        Container(erp_sync, "ERP Sync gate", "Sync data with ERP")
        System_Ext(erp, "ERP - system")
        BiRel(erp, erp_sync, "sync data")
        ContainerQueue(events_hub, "Events Hub", "Store structured data, communicate between services")
    
    }
    Rel(internal_services, data_hub, "raw data")
   
    Container(api_local, "Local API - Gateaway")
    BiRel(events_hub, api_local, "uses")
    
}

System_Boundary(atck_server, "Server"){
    ContainerQueue(events_hub_server, "Structured Data Storage", "Collects structured data from agents")
    BiRel(events_hub, events_hub_server, "sync data")
   
    
    Boundary(analysis_internal, "Internal Analytic Services"){
        Container(metrics_management, "Metrics management", "Create, modify, remove metrics")
        Container(analytic_module_sync, "Analytic Sync gate", "Send metrics data to external analytics module")   
        System_Ext(analytic_module, "Analytic Module") 
        Rel(analytic_module_sync, analytic_module ,"send metrics")
        ContainerDb(analytic_db, "Analytic data storage")
    }
    ContainerDb(data_hub_server, "Raw Data storage", "Collects raw data from agents")
    Rel(data_hub, data_hub_server ,"send raw data")
    Rel(data_hub_server, analysis_internal, "request data for metrics")
    
    Container(api, "API - Gateaway")
    BiRel(api, analysis_internal, "uses")
    BiRel(events_hub_server, api, "uses")
   
    
}
 Boundary(b_ui, "User Interface"){
        
        Container(ui, "Mobile or Web application")
        Person(operator, "Operator")
        Person(analytic, "Analytic")
        Person(vet, "Vet")
        BiRel(ui, operator, "Uses: tasks")
        BiRel(ui, vet, "Uses: health data for pigs")
        BiRel(ui, analytic, "Uses: metrics")
        BiRel(ui,api, "uses")
        BiRel(ui,api_local, "uses")
    
    }