@startuml Архитектура_АвтоТехноСвиноКомплекс_v1
!include <C4/C4_Container>
Person(duty_operator, "Duty Operator")

System_Boundary(atck_agent, "Agent"){
    ContainerQueue(broker, "Message broker")
    Container(video, "Video analysis")
    Rel(video, broker, "send events")

    Container(notification, "Notifications")
    Rel(video, notification, "send notification")
    Rel(notification, duty_operator, "Recieves notification")
    
    Container(iot, "IOT data collecting")
    Rel(iot, broker, "sensors data", "MQTT")
    Rel(iot, broker, "RFID data", "MQTT")
}

System_Boundary(atck_server, "Server"){
    ContainerQueue(event_broker, "Event broker")
    
        ContainerQueue(broker_server, "Message broker")
        BiRel(broker, broker_server, "sync data")
        Container(data, "Data Lake")
        Rel(broker_server, data, "raw data from Iot sensors")

        Container(iot_management, "Manage IoT devices")
        Rel(iot_management, data, "request data")
        Rel(iot_management, broker_server, "commands for IoT device")
        Rel(iot_management, event_broker, "tasks for people")     
    
   
    Boundary(internal_services, "Internal services"){
        Container(prediction, "Prediction data service")
        Rel(prediction, data, "request data")
        Rel(prediction, event_broker, "commands for erp (buy food for pigs)")
            
        Container(pigs, "Pigs management")
        Rel(pigs, data, "request data")
        Rel(pigs, event_broker, "pigs data")
        
    }
    Container(tasks, "Tasks management")
    Rel(event_broker, tasks, "get commands for people")
    Rel(event_broker, tasks, "get results of command executions")
    Rel(event_broker, tasks, "get people data (ERP)")
    Rel(tasks, event_broker, "send personificated commands")

    System_Ext(erp, "ERP - system")
    Container(erp_sync, "ERP Sync gate")
    BiRel(erp_sync, event_broker, "send ERP-data")
    BiRel(erp, erp_sync, "Sync data")
    
    System_Ext(analytic_module, "Analytic Module")
    
    Container(analytic_module_sync, "Analytic Sync gate")
    Rel(data, analytic_module_sync, "send metrics data")
    Rel(analytic_module_sync, analytic_module ,"send metrics data")
    
    Container(metrics, "Manage metrics")
    Rel(metrics, data, "create new metrics")
    Rel(data, metrics, "request metrics data")

    Container(ui, "Mobile or Web application")
    Boundary(users,"Users" ){
        Person(operator, "Operator")
        Person(analytic, "Analytic")
        Person(vet, "Vet")
    }
    Rel(ui, operator, "Uses: tasks")
    Rel(ui, vet, "Uses: health data for pigs")
    Rel(analytic, ui, "Uses: metrics")
    BiRel(ui, event_broker, "send/receive commands")
    BiRel(ui, metrics, "get metrics data and manage metrics")
    
}
Lay_D(event_broker, internal_services)
@enduml