@startuml Architecture_C4_Containers
!include <C4/C4_Container>

Person(duty_operator, "Дежурный оператор")
Person(operator, "Оператор")
Person(analytic, "Аналитик")
Person(vet, "Ветеринар")

System(atck_server, "Сервер1")
System_Ext(analytic_module, "Аналитический модуль")
System_Ext(erp, "ERP - система")

System_Boundary(atck_agent, "Агент1"){
    Container(video, "Сервис видеоанализа")
    Container(iot, "Сервис умных устройств")
    Container(notification, "Сервис оповещения")
    Container(broker, "Брокер сообщений")
}

@enduml