name: PlantUML Diagrams

on:
  push:
    branches:
      - main
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
  pull_request:
    branches:
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install PlantUML
      run: sudo apt-get install plantuml

    - name: Generate Diagrams
      run: |
        plantuml Task1/ATCK_C4_Context_alternative.puml
        plantuml Task2/*.puml
        plantuml Task3/*.puml
        plantuml Task4/*.puml
        plantuml Task5/*.puml

    - name: Commit Diagrams
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add **/*.png
        git commit -m "Automated diagram generation"
        git push origin main
      if: success() 