name: Export PlantUML diagrams

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Graphviz
        run: sudo apt-get install graphviz
      
      - name: Install PlantUML
        run: sudo apt-get install plantuml

      - name: Get all changes files
        id: get-changed-files
        uses: jitterbit/get-changed-files@v1
      
      - name: Get changed UML files
        id: get-changed-uml-files
        run: |
          puml_files=''
          for changed_file in ${{ steps.get-changed-files.outputs.modified }}; do
            extension="${changed_file##*.}"

            if [ "${extension}" == "puml" ]; then
              # add puml file
              puml_files="${puml_files} ${changed_file}"
              echo "Added file: ${changed_file}"
            fi
          done
          echo "puml-files=${puml_files}" >> $GITHUB_OUTPUT  

      - name: Generate SVG Diagrams
        id: get-generated-images
        run: |
          for puml_file in ${{ steps.get-changed-files.outputs.puml-files }}; do
            plantuml ${puml_file}"

      - name: Commit Diagrams
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add **/*.png
          git commit -m "Automated diagram generation"
          git push origin main
        if: success() 